Debuggability methods
bem-sdk/bem-cell pull request #10
Opened 2017-01-17 21:59 UTC by zxqfox

2017-01-17 22:59 UTC, tadatuta approved these changes

2017-01-17 22:59 UTC, tadatuta commented on README.md
> +Returns string representing this cell.
Returns a string

2017-01-17 22:59 UTC, tadatuta commented on README.md
> +Returns object representing this cell.
Returns an object

2017-01-17 22:59 UTC, tadatuta commented on README.md
> +Returns object for `JSON.stringify()` purposes.
Returns an object

and not sure about `purposes`, shouldn't it be in singular?

2017-01-17 22:59 UTC, tadatuta commented on README.md
> +You can also convert `BemCell` object to `string`.
to `string` -> to a string

2017-01-17 23:53 UTC, zxqfox commented
@tadatuta <3 ty

2017-01-18 12:36 UTC, blond requested changes

2017-01-18 12:36 UTC, blond commented on README.md
> +cell.toString(); // button_focused
Лучше все поля в примере показать, чтобы не путать с `BemEntityName`.

2017-01-18 12:36 UTC, blond commented on README.md
> +// ➜ { entity: { block: 'button', mod: { name: 'focused', value: true } } }
и тут лучше все поля показать

2017-01-18 12:36 UTC, blond commented on index.js
> +     * The representation object contains only `block`, `elem` and `mod` fields
не нужно уточнить, что это про `entity` поле?

2017-01-18 12:36 UTC, blond commented on test/to-string.test.js
> +    t.truthy(typeof cell.toString() === 'string');
Может ещё проверять, что `id` равен `toString`?

2017-01-24 06:44 UTC, Yeti-or commented on index.js
> +    toString() { return this.id; }
by the way why not
`path.join(this.layer || '', this.entity)` ?

2017-01-26 20:04 UTC, zxqfox commented on test/to-string.test.js
> +    t.truthy(typeof cell.toString() === 'string');
А точно есть смысл? Нам же не особо важен формат

2017-01-26 20:10 UTC, blond approved these changes

2017-01-26 22:06 UTC, merged