BemCell.create method
bem-sdk/bem-cell pull request #13
Opened 2017-01-26 22:18 UTC by zxqfox

cc @Yeti-or @blond @tadatuta

2017-01-27 04:48 UTC, skad0 commented on README.md
> +### #create(object)
а что означает # перед названием?

2017-01-27 04:54 UTC, skad0 requested changes

2017-01-27 04:54 UTC, skad0 commented on README.md
> +Helper for laziness.
)))
Может тогда lazybones?

2017-01-27 04:54 UTC, skad0 commented on test/create.test.js
> +    const data = { block: 'b', elem: 'e' };
зачем тут элемент? Да и кажется переменная не требуется (как в тесте ниже)

2017-01-27 04:54 UTC, skad0 commented on test/create.test.js
> +    const cell = BemCell.create({ block: 'block', tech: 'css' });
надо еще добавить тест про `BemCell.create({ entity, tech, layer })`

2017-01-31 12:55 UTC, zxqfox commented on README.md
> +### #create(object)
Статический метод. Можно как-то иначе их обозначать, это такое.

2017-01-31 18:11 UTC, zxqfox commented on test/create.test.js
> +    const cell = BemCell.create({ block: 'block', tech: 'css' });
done

2017-01-31 18:12 UTC, Yeti-or commented on README.md
> +Creates BemCell instance by the any object representation.
without `the`

2017-01-31 18:17 UTC, Yeti-or commented on index.js
> +     * Creates BemCell instance by the any object representation.
the

2017-01-31 18:25 UTC, Yeti-or requested changes

2017-01-31 18:25 UTC, Yeti-or commented on index.js
> +     * @param {string} obj.mod.name — the modifier name of entity.
optional

2017-01-31 18:25 UTC, Yeti-or commented on index.js
> +        if (BemCell.isBemCell(obj)) {
what s the purpose ?

2017-01-31 18:56 UTC, zxqfox commented on index.js
> +        if (BemCell.isBemCell(obj)) {
To prevent creating BemCells from BemCells

2017-01-31 18:57 UTC, zxqfox commented on index.js
> +     * @param {string} obj.mod.name — the modifier name of entity.
no, it's not if obj.mod is an object

2017-01-31 20:33 UTC, tadatuta approved these changes
👍

2017-02-01 12:43 UTC, Yeti-or commented on index.js
> +     * @param {string} obj.mod.name — the modifier name of entity.
ок

2017-02-01 12:45 UTC, Yeti-or approved these changes

2017-02-01 12:48 UTC, skad0 approved these changes

2017-02-01 14:30 UTC, merged