Add is-equal method
bem-sdk/bem-cell pull request #20
Opened 2017-02-10 13:28 UTC by skad0

2017-02-11 03:51 UTC, Yeti-or requested changes

2017-02-11 03:51 UTC, Yeti-or commented on README.md
> +Determines whether specified cell is deep equal cell.
I think that when you use whether, you need to provide choices:
```
Determines whether specified cell is deep equal to cell or not.
```

2017-02-11 03:51 UTC, Yeti-or commented on README.md
> +buttonCell.isEqual(buttonCell); // true
maybe it is better to provide an example with comparing to another cell?
not to itself, just to add more clearance.

2017-02-11 03:51 UTC, Yeti-or commented on index.js
> +     * @returns {Boolean} - A boolean indicating whether or not scecified cell is deep equal
boolean is an adjective.

2017-02-11 03:51 UTC, Yeti-or commented on test/is-equal.test.js
> +test('should not detect equal cell by entity', t => {
maybe:
`should detect that cells are not equal by entity` ?

2017-02-11 03:51 UTC, Yeti-or commented on test/is-equal.test.js
> +    t.true(cell.isEqual(cell));
I don't like that it's checking same instance

2017-02-11 15:23 UTC, zxqfox commented on README.md
> +    entity: new BemEntityName({ block: 'button' }), tech: 'css', layer: 'desktop'
Why not to use `BemCell.create` here to reduce noise?

2017-02-11 16:05 UTC, qfox requested changes

2017-02-11 16:05 UTC, qfox commented on index.js
> +     *
No need to left this line

2017-02-14 08:08 UTC, skad0 commented on index.js
> +     *
There are empty lines before `@returns` in other jsdoc here

2017-02-14 08:09 UTC, zxqfox commented on index.js
> +     *
It's incorrect ;-)

2017-02-14 09:03 UTC, skad0 commented
:up:

2017-02-14 10:58 UTC, zxqfox commented on README.md
> +const BemEntityName = require('@bem/entity-name');
Let's use `BemCell.create`?

2017-02-14 11:39 UTC, skad0 commented on README.md
> +const BemEntityName = require('@bem/entity-name');
ok, rdy

2017-02-14 17:25 UTC, skad0 commented
:up:

2017-02-14 17:32 UTC, qfox requested changes
В остальном ок

2017-02-14 17:32 UTC, zxqfox commented on README.md
> +    entity: { block: 'button' }, tech: 'css', layer: 'desktop'
можно еще от `entity: {}` избавиться, оставить только `block: 'button'`, нам же оно не особо здесь нужно?

2017-02-14 17:32 UTC, zxqfox commented on index.js
> +     * const BemEntityName = require('@bem/entity-name');
Здесь пример не очень

2017-02-14 17:48 UTC, skad0 commented
:up:

2017-02-14 19:03 UTC, zxqfox commented on README.md
> +});
Давай в одну строку!

2017-02-14 19:07 UTC, skad0 commented on README.md
> +});
Дал

2017-02-14 19:14 UTC, zxqfox commented
and rename commit: `feat: isEqual method`

2017-02-14 19:17 UTC, qfox approved these changes

2017-02-14 19:19 UTC, blond requested changes
Не хватает тестов для случаев когда часть полей совпадает, часть нет. И когда в одном `cell` поля указаны, а в другом нет.

2017-02-14 19:20 UTC, Yeti-or approved these changes

2017-02-14 19:20 UTC, Yeti-or commented on index.js
> +     * @returns {Boolean} - A boolean value indicating whether or not specified cell is deep equal
is deep equal to what?

2017-02-14 19:20 UTC, Yeti-or commented on index.js
> +     * @returns {Boolean} - A boolean value indicating whether or not specified cell is deep equal
What a about remove line after describing what it returns ? cause it's seem obvious

2017-02-14 19:22 UTC, skad0 commented
>Не хватает тестов для случаев когда часть полей совпадает, часть нет

Не понял, ты про разницу внутри entity? Если да, то это же про bem-entity-name?

2017-02-14 19:32 UTC, skad0 commented
@blond 
:up:

2017-02-14 19:34 UTC, blond approved these changes

2017-02-14 19:40 UTC, merged