feat: #17 Add 'Deprecated' info wherever used 'modName, modVal'
bem-sdk/bem-cell pull request #24
Opened 2017-02-17 10:01 UTC by birhoff

- add deprecated logs
 - add deprecated JSDoc
 - remove deprecated examples

2017-02-17 18:06 UTC, zxqfox commented
Oh, hm. Something happened with tests?

2017-02-17 18:11 UTC, zxqfox commented
Can we make env variable to enable these warnings?
I think we should wait for the next major with real deprecations of methods.

2017-02-17 18:14 UTC, zxqfox commented on index.js
> +     * @param {string} [obj.modVal] — the modifier value of entity. Used if neither `mod.val` nor `val` were not
Не, тут не надо отрывать, только геттеры.

2017-02-21 17:10 UTC, birhoff commented
@zxqfox What we do with this?

2017-02-21 17:18 UTC, zxqfox commented on index.js
> -     * BemCell.create({ entity: { block: 'my-button', modName: 'theme', modVal: 'red' }, tech: 'css' });
Verni!

2017-02-21 22:55 UTC, Yeti-or requested changes

2017-02-21 22:55 UTC, Yeti-or commented on index.js
> +const deprecate = require('depd')('bem-cell');
And what is purpose of this module here?
why is it better than just `console.warn('modName: just for compatibility and can be dropped in future')` ?

2017-02-22 13:16 UTC, birhoff commented on index.js
> +const deprecate = require('depd')('bem-cell');
- you cant disable console.log throw ENV
- its colorized
- deprecated is always need :)

2017-02-22 13:22 UTC, birhoff commented
🆙 Need squash before merge

2017-02-22 20:09 UTC, tadatuta commented
let's also provide info about methods to use instead of deprecated ones

2017-02-23 00:12 UTC, birhoff commented
🆙 @tadatuta

2017-02-23 03:24 UTC, Yeti-or approved these changes

2017-03-08 15:41 UTC, blond commented on index.js
> +        console.warn('modName: just for compatibility and can be dropped in future. Instead use \'mod.name\'');
Как по мне, нельзя ничего писать в консоль.

Может кто-то парсит `stdout` и это сообщение всё сломает.

2017-03-09 11:50 UTC, birhoff commented
Когда решите что хотите, пишите=)

2017-03-09 12:50 UTC, blond commented
> Когда решите что хотите, пишите=)

Ну вот, обиделся :(

2017-03-10 10:06 UTC, birhoff commented
Да нет, просто, я уже 3 раза переделывал эти 3 строки. Давайте вольем без варнингов или с `depd`. 

Я бы делал с `depd` потому что его через переменные окружения можно выключить что позволит тем кто парсит stdout продолжить это делать.

2017-03-10 11:42 UTC, blond commented
Мне вариант с `depd` нравится, но соглашусь и с вариантом просто без варнингов, если есть причины.

2017-03-10 12:18 UTC, blond commented on package.json
> +    "depd": "^1.1.0"
мы используем только точные версии в `dependencies`

2017-03-10 12:19 UTC, blond approved these changes

2017-03-10 12:28 UTC, birhoff commented on package.json
> +    "depd": "^1.1.0"
Что то я не видел этого в гайде=)

2017-03-10 12:52 UTC, Yeti-or commented
А почему не использовать `util.deprecate`

2017-03-10 13:08 UTC, birhoff commented
Оно содержит больше информации, для того, чтоб легко было определить где именно ты использовал то, что устарело

2017-03-11 11:13 UTC, birhoff commented
What we wait now guys?

2017-03-12 16:09 UTC, Yeti-or approved these changes
может уже сквошь ребейщь вливай

2017-03-13 17:36 UTC, merged